-- MySQL Script generated by MySQL Workbench
-- Sunday 12 November 2017 06:01:09 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema QOC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema QOC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QOC` DEFAULT CHARACTER SET utf8 ;
USE `QOC` ;

-- -----------------------------------------------------
-- Table `QOC`.`ORG_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`ORG_TYPE` ;

CREATE TABLE IF NOT EXISTS `QOC`.`ORG_TYPE` (
  `ORG_TYPE_ID` DOUBLE NOT NULL,
  `PARTY_NAME` VARCHAR(255) NULL,
  `EFFECTIVE_DATE` DATE NULL,
  `EFECTIVE_END` DATE NULL,
  PRIMARY KEY (`ORG_TYPE_ID`))
ENGINE = InnoDB
COMMENT = 'THIS TABLE WILL SUGGEST TEH CUSTOMER OR ORGANIZAIONTYPE OR SUPPLIER TYPE ETC ';


-- -----------------------------------------------------
-- Table `QOC`.`COUNTRY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`COUNTRY` ;

CREATE TABLE IF NOT EXISTS `QOC`.`COUNTRY` (
  `COUTNRY_ID` DOUBLE NOT NULL,
  `COUNTRY_NAME` MEDIUMTEXT NULL,
  PRIMARY KEY (`COUTNRY_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`STATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`STATE` ;

CREATE TABLE IF NOT EXISTS `QOC`.`STATE` (
  `STATE_ID` DOUBLE NOT NULL,
  `STATE_NAME` MEDIUMTEXT NULL,
  `COUNTRY_ID` DOUBLE NULL,
  PRIMARY KEY (`STATE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`CITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`CITY` ;

CREATE TABLE IF NOT EXISTS `QOC`.`CITY` (
  `CITY_ID` DOUBLE NOT NULL,
  `CITY_NAME` MEDIUMTEXT NULL,
  `CONTRY_ID` DOUBLE NULL,
  `STATE_ID` DOUBLE NULL,
  PRIMARY KEY (`CITY_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`ADDRESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`ADDRESS` ;

CREATE TABLE IF NOT EXISTS `QOC`.`ADDRESS` (
  `ADDRESS_ID` DOUBLE NOT NULL,
  `ADDRESS_TYPE` VARCHAR(45) NULL,
  `BUILDING_NUMBER` VARCHAR(45) NULL,
  `STREET_ADDRESS` VARCHAR(255) NULL,
  `AREA` VARCHAR(255) NULL,
  `LANDMARK` MEDIUMTEXT NULL,
  `CITY_ID` DOUBLE NULL,
  `STATE_ID` DOUBLE NULL,
  `COUNTRY_ID` DOUBLE NULL,
  PRIMARY KEY (`ADDRESS_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`contact` ;

CREATE TABLE IF NOT EXISTS `QOC`.`contact` (
  `contact_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contact_type` INT(11) UNSIGNED NULL,
  `contact` VARCHAR(255) NULL,
  `party_id` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`contact_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`DOMAIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`DOMAIN` ;

CREATE TABLE IF NOT EXISTS `QOC`.`DOMAIN` (
  `DOMAIN_ID` DOUBLE NOT NULL,
  `DOMAIN_NAME` MEDIUMTEXT NULL,
  `ORG_ID` DOUBLE NULL COMMENT 'FORIENG OF orGANIZATION',
  PRIMARY KEY (`DOMAIN_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`SUB_ORGANIZATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`SUB_ORGANIZATION` ;

CREATE TABLE IF NOT EXISTS `QOC`.`SUB_ORGANIZATION` (
  `SUB_ORGANIZATION_ID` DOUBLE NOT NULL,
  `SUB_ORGANIZATION_NAME` VARCHAR(255) NULL,
  `ORGANIZATION_ID` DOUBLE NULL,
  PRIMARY KEY (`SUB_ORGANIZATION_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`MASTER_COMPANY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`MASTER_COMPANY` ;

CREATE TABLE IF NOT EXISTS `QOC`.`MASTER_COMPANY` (
  `MASTER_COMPANY_ID` DOUBLE NOT NULL,
  `MASTER_COMPANY_NAMEl` VARCHAR(255) NULL,
  `MASTER_COMPANY_CURRENCY` VARCHAR(45) NULL,
  `EFFECTIVE_DATE` DATE NULL,
  `EFFECTIVE_ENDDATE` DATE NULL,
  `ADDRESS_ID` DOUBLE NULL,
  `CONTACT_ID` DOUBLE NULL,
  PRIMARY KEY (`MASTER_COMPANY_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`LEAD_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`LEAD_TYPE` ;

CREATE TABLE IF NOT EXISTS `QOC`.`LEAD_TYPE` (
  `LEAD_TYPE_ID` DOUBLE NOT NULL,
  `LEAD_TYPE_NAME` VARCHAR(255) NULL,
  PRIMARY KEY (`LEAD_TYPE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`ORGANIZATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`ORGANIZATION` ;

CREATE TABLE IF NOT EXISTS `QOC`.`ORGANIZATION` (
  `ORGANIZATION_ID` DOUBLE NOT NULL,
  `ORGANIZATION_NAME` MEDIUMTEXT NULL,
  `SUB_ORGANIZATION_ID` DOUBLE NULL,
  `EFFECTIVE_DATE` DATE NULL,
  `EFFECTIVE_ENDDATE` DATE NULL,
  `ORG_TYPE_ID` DOUBLE NULL,
  `ADDRESS_ID` DOUBLE NULL,
  `CONTACT_ID` DOUBLE NULL,
  `LAST_CONTACTED` DATE NULL,
  `APPOINTMENT_DATE` DATE NULL,
  `FOLLOWUP` INT NULL,
  `LEAD_TYPE_ID` DOUBLE NULL COMMENT 'WILL HAVE DROP DOWN VALUE \nNEUTRAL\nGIID \nVERY GOOD\nREJECTED\nBUSINESS CLOSED',
  `DOMAIN_ID` DOUBLE NULL,
  `MASTER_COMPANY_ID` DOUBLE NULL,
  PRIMARY KEY (`ORGANIZATION_ID`))
ENGINE = InnoDB
COMMENT = 'IT WILL STORY ATTRIBUTE OF AN ORGANIZATION - LIKE NAME ETC, ACTIVE OR EXPIRED ETC - \nTABLE WILL BE REFFERED AT SCREEN LIKE OPPORTUNITY, CUSTOMER, LEAD ETC.';


-- -----------------------------------------------------
-- Table `QOC`.`CONTACT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`CONTACT` ;

CREATE TABLE IF NOT EXISTS `QOC`.`CONTACT` (
  `CONTACT_ID` DOUBLE NOT NULL,
  `TITLE` VARCHAR(45) NULL,
  `FIRST_NAME` MEDIUMTEXT NULL,
  `MIDDLE_NAME` MEDIUMTEXT NULL,
  `LAST_NAME` MEDIUMTEXT NULL,
  `PRIMARY_NUMBER` VARCHAR(45) NULL,
  `SECONDARY_NUMBER` VARCHAR(45) NULL,
  `CELL_NUMBER` VARCHAR(45) NULL,
  `EMAIL_ID` MEDIUMTEXT NULL,
  `CONTACT_TYPE` VARCHAR(45) NULL COMMENT 'WILL SUGGEST IF THE CONTACT IS PRIMARY OR SECONDRY OR OTHER CONTACT',
  `ORGANIZATION_ID` DOUBLE NULL,
  `ADDRESS_ID` DOUBLE NULL,
  PRIMARY KEY (`CONTACT_ID`))
ENGINE = InnoDB
COMMENT = 'TABLE WILL STORE ALL THE DETAILS WITH RESPECT TO AN INDVIDUAL WITH FIRST NAME AND LAST NAME ACCROSS DATABASE';


-- -----------------------------------------------------
-- Table `QOC`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `QOC`.`PRODUCT` (
  `PRODUCT_ID` DOUBLE NOT NULL,
  `ORGANIZATION_ID` DOUBLE NULL,
  `PARENT_PRODUCT_ID` DOUBLE NULL,
  `PRODUCT_NAME` MEDIUMTEXT NULL,
  `PRODUCT_SUPPLIER_ID` MEDIUMTEXT NULL,
  `PRODUCT_UOM` DOUBLE NULL,
  `PRODUCT_CATEGORY` MEDIUMTEXT NULL,
  `PRODUCT_COST` FLOAT NULL,
  `PRODUCT_MARGIN_PERCENTAGE` FLOAT NULL,
  `PRODUCT_DISCOUNT_THRESHOLD` FLOAT NULL,
  `PRODUCT_GST` FLOAT NULL,
  `PRODUCT_CAVEATS` LONGTEXT NULL,
  `PRODUCT_MANDATORY_PARTS` TEXT NULL COMMENT 'WE SHOULD HAVE \nCOMMA SEPRATED\nVALUES TO READ WITH PRODUCT ID',
  `PRODUCT_NOTES` VARCHAR(45) NULL,
  `MASTER_COMPANY_ID` DOUBLE NULL,
  PRIMARY KEY (`PRODUCT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`USER` ;

CREATE TABLE IF NOT EXISTS `QOC`.`USER` (
  `USER_ID` DOUBLE NOT NULL,
  `USER_NAME` MEDIUMTEXT NULL,
  `USER_PASSWORD` VARCHAR(45) NULL,
  `CONTACT_ID` DOUBLE NULL,
  `USER_ROLE` MEDIUMTEXT NULL,
  `DESIGNATION` MEDIUMTEXT NULL,
  `EFFECTIVE_DATE` DATE NULL,
  `EFFECTIVE_ENDDATE` DATE NULL,
  `MASTER_COMPANY_ID` DOUBLE NULL,
  `ORGANIZATION_ID` DOUBLE NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`BUNDLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`BUNDLE` ;

CREATE TABLE IF NOT EXISTS `QOC`.`BUNDLE` (
  `BUNDLE_ID` DOUBLE NULL,
  `BUNDLE_NAME` VARCHAR(255) NULL,
  `GENERIC` TINYINT(1) NULL,
  `PRODUCT_ID` DOUBLE NULL COMMENT 'need to find how to associate multiple product',
  `MASTER_COMPANY_id` DOUBLE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`EXCHANGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`EXCHANGE` ;

CREATE TABLE IF NOT EXISTS `QOC`.`EXCHANGE` (
  `CURRENCY_CODE` TEXT NOT NULL,
  `CURRENCY_NAME` MEDIUMTEXT NULL,
  `EXCHANGE_RATE` DOUBLE NULL,
  `MASTER_COMPANY_ID` DOUBLE NULL,
  PRIMARY KEY (`CURRENCY_CODE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`SUPPLIER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`SUPPLIER` ;

CREATE TABLE IF NOT EXISTS `QOC`.`SUPPLIER` (
  `SUPPLIER_ID` DOUBLE NOT NULL,
  `SUPPLIER_NAME` MEDIUMTEXT NULL,
  `CONTACT_ID` DOUBLE NULL,
  `ADDRESS_ID` DOUBLE NULL,
  `EFFECTIVE_DATE` DATE NULL,
  `EFFECTIVE_ENDDATE` DATE NULL,
  PRIMARY KEY (`SUPPLIER_ID`))
ENGINE = InnoDB
COMMENT = 'TABLE KEEPS SUPPLIER DETAILS LIKE NAME - ADDRESS DETAILS ETC\nSUPPLIER CONTACT';


-- -----------------------------------------------------
-- Table `QOC`.`SITES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`SITES` ;

CREATE TABLE IF NOT EXISTS `QOC`.`SITES` (
  `SITE_ID` DOUBLE NOT NULL,
  `SITE_NAME` MEDIUMTEXT NULL,
  `ADDRESS_ID` DOUBLE NULL,
  `CONTACT_ID` DOUBLE NULL,
  `ORGANIZATION_ID` DOUBLE NULL,
  `SITE_TYPE` VARCHAR(45) NULL COMMENT 'SHOULD HAVE LIKE BRANCH SITE OR CORPORATE OFFICE',
  PRIMARY KEY (`SITE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`party_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`party_type` ;

CREATE TABLE IF NOT EXISTS `QOC`.`party_type` (
  `party_type_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `party_type_name` VARCHAR(255) NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`party_type_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`party`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`party` ;

CREATE TABLE IF NOT EXISTS `QOC`.`party` (
  `party_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `party_type_id` INT(11) UNSIGNED NOT NULL,
  `party_name` VARCHAR(255) NULL,
  `party_type` INT(11) UNSIGNED NULL,
  `partent_party_id` INT(11) UNSIGNED NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`party_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `party_FKIndex1` ON `QOC`.`party` (`party_type_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`Address_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Address_type` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Address_type` (
  `address_type_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `address_type` VARCHAR(255) NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`address_type_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Country` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Country` (
  `country_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Country_name` VARCHAR(255) NULL,
  PRIMARY KEY (`country_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`address` ;

CREATE TABLE IF NOT EXISTS `QOC`.`address` (
  `address_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Country_country_id` INT(11) UNSIGNED NOT NULL,
  `Address_type_address_type_id` INT(11) UNSIGNED NOT NULL,
  `address_type_id` INT(11) UNSIGNED NULL,
  `address1` VARCHAR(255) NULL,
  `address2` VARCHAR(255) NULL,
  `city_id` INT(11) UNSIGNED NULL,
  `pin` INT(11) UNSIGNED NULL,
  `state_id` INT(11) UNSIGNED NULL,
  `countr_id` INT(11) UNSIGNED NULL,
  `party_id` INT(11) UNSIGNED NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`address_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `address_FKIndex1` ON `QOC`.`address` (`Address_type_address_type_id` ASC);

CREATE INDEX `address_FKIndex2` ON `QOC`.`address` (`Country_country_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`Organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Organization` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Organization` (
  `Organization_id` DOUBLE NOT NULL AUTO_INCREMENT,
  `Organization_name` VARCHAR(255) NOT NULL,
  `Parent_Organization_id` DOUBLE NULL,
  `Effective_date` DATE NULL,
  `End_date` DATE NULL,
  `Party_id` INT(11) UNSIGNED NULL,
  `address_id` INT(11) UNSIGNED NULL,
  `contact_id` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`Organization_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `Organization_FKIndex1` ON `QOC`.`Organization` (`address_id` ASC);

CREATE INDEX `Organization_FKIndex2` ON `QOC`.`Organization` (`contact_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`Product_Master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Product_Master` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Product_Master` (
  `Product_Id` DOUBLE NOT NULL AUTO_INCREMENT,
  `Product_Name` VARCHAR(255) NOT NULL,
  `Parent_Product_id` DOUBLE NULL,
  `Organization_id` DOUBLE NULL,
  `Effective_date` DATE NULL,
  `End_date` DATE NULL,
  PRIMARY KEY (`Product_Id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `Product_Master_FKIndex1` ON `QOC`.`Product_Master` (`Organization_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`Product_Attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Product_Attribute` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Product_Attribute` (
  `Attribute_id` DOUBLE NOT NULL AUTO_INCREMENT,
  `Attribute_Name` VARCHAR(255) NOT NULL,
  `Effective_date` DATE NOT NULL,
  `End_Date` DATE NULL,
  `Parent_Attribute_id` DOUBLE NULL,
  `Price` FLOAT NULL,
  `part_number` TEXT NULL,
  PRIMARY KEY (`Attribute_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`quote_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`quote_master` ;

CREATE TABLE IF NOT EXISTS `QOC`.`quote_master` (
  `quote_id` DOUBLE NOT NULL AUTO_INCREMENT,
  `quote_name` VARCHAR(255) NOT NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  `party_id` INT(11) UNSIGNED NULL,
  `address_id` INT(11) UNSIGNED NULL,
  `contact_id` INT(11) UNSIGNED NULL,
  `version` VARCHAR(255) NOT NULL,
  `Price` FLOAT NULL,
  `Discounts` FLOAT NULL,
  `comments` VARCHAR(255) NULL,
  PRIMARY KEY (`quote_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `quote_master_FKIndex1` ON `QOC`.`quote_master` (`party_id` ASC);

CREATE INDEX `quote_master_FKIndex2` ON `QOC`.`quote_master` (`contact_id` ASC);

CREATE INDEX `quote_master_FKIndex3` ON `QOC`.`quote_master` (`address_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`price_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`price_book` ;

CREATE TABLE IF NOT EXISTS `QOC`.`price_book` (
  `price_book_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `price_book_name` TEXT NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`price_book_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`Price_book_attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Price_book_attribute` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Price_book_attribute` (
  `price_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Product_Attribute_Attribute_id` DOUBLE NOT NULL,
  `price_book_id` INT(11) UNSIGNED NOT NULL,
  `price_book_name` TEXT NULL,
  `attribute_id` INT(11) UNSIGNED NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`price_id`, `Product_Attribute_Attribute_id`, `price_book_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `Price_book_attribute_FKIndex1` ON `QOC`.`Price_book_attribute` (`Product_Attribute_Attribute_id` ASC);

CREATE INDEX `Price_book_attribute_FKIndex2` ON `QOC`.`Price_book_attribute` (`price_book_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`quote_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`quote_details` ;

CREATE TABLE IF NOT EXISTS `QOC`.`quote_details` (
  `quote_detail_id` DOUBLE NOT NULL AUTO_INCREMENT,
  `Price_book_attribute_price_book_id` INT(11) UNSIGNED NOT NULL,
  `Price_book_attribute_Product_Attribute_Attribute_id` DOUBLE NOT NULL,
  `Price_book_attribute_price_id` INT(11) UNSIGNED NOT NULL,
  `quote_id` DOUBLE NULL,
  `product_id` DOUBLE NULL,
  `attribute_id` DOUBLE NULL,
  `price` FLOAT NULL,
  `discounts` FLOAT NULL,
  `comments` VARCHAR(255) NULL,
  `quantity` INT(11) UNSIGNED NULL,
  `price_book_id` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`quote_detail_id`, `Price_book_attribute_price_book_id`, `Price_book_attribute_Product_Attribute_Attribute_id`, `Price_book_attribute_price_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `quote_details_FKIndex1` ON `QOC`.`quote_details` (`quote_id` ASC);

CREATE INDEX `quote_details_FKIndex2` ON `QOC`.`quote_details` (`Price_book_attribute_price_id` ASC, `Price_book_attribute_Product_Attribute_Attribute_id` ASC, `Price_book_attribute_price_book_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`state` ;

CREATE TABLE IF NOT EXISTS `QOC`.`state` (
  `state_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Country_country_id` INT(11) UNSIGNED NOT NULL,
  `state_name` VARCHAR(255) NULL,
  `country_id` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`state_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `state_FKIndex1` ON `QOC`.`state` (`Country_country_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`city` ;

CREATE TABLE IF NOT EXISTS `QOC`.`city` (
  `city_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Country_country_id` INT(11) UNSIGNED NOT NULL,
  `city_name` VARCHAR(255) NULL,
  `state_id` INT(11) UNSIGNED NULL,
  `country_id` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`city_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `city_FKIndex1` ON `QOC`.`city` (`Country_country_id` ASC);

CREATE INDEX `city_FKIndex2` ON `QOC`.`city` (`state_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`Product_configuration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Product_configuration` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Product_configuration` (
  `Product_config_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Product_Master_Product_Id` DOUBLE NOT NULL,
  `Product_Attribute_Attribute_id` DOUBLE NOT NULL,
  `Product_id` INT(11) UNSIGNED NULL,
  `Product_name` TEXT NULL,
  `attribute_id` INT(11) UNSIGNED NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  `quantity` INT(11) UNSIGNED NULL,
  `Non_standard_text` TEXT NULL,
  PRIMARY KEY (`Product_config_id`, `Product_Master_Product_Id`, `Product_Attribute_Attribute_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `Product_configuration_FKIndex1` ON `QOC`.`Product_configuration` (`Product_Master_Product_Id` ASC);

CREATE INDEX `Product_configuration_FKIndex2` ON `QOC`.`Product_configuration` (`Product_Attribute_Attribute_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`Order_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Order_master` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Order_master` (
  `Order_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Quote_id` INT(11) UNSIGNED NULL,
  `Order_status` INT(11) UNSIGNED NULL,
  `Invoice_id` INT(11) UNSIGNED NULL,
  `Percentage_completed` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`Order_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Invoice` (
  `Invoice_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Invoice_date` DATE NULL,
  `Quote_id` INT(11) UNSIGNED NULL,
  `Order_id` INT(11) UNSIGNED NULL,
  `Customer_name` TEXT NULL,
  `Customer_address_line1` TEXT NULL,
  `Customer_address_line2` TEXT NULL,
  `City` TEXT NULL,
  `State` TEXT NULL,
  `Country` TEXT NULL,
  `Invoice_status` INT(11) UNSIGNED NULL,
  `Contact_number` TEXT NULL,
  `Quote_version` TEXT NULL,
  `price` FLOAT NULL,
  `discount` FLOAT NULL,
  `comments` TEXT NULL,
  PRIMARY KEY (`Invoice_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`Invoice_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Invoice_details` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Invoice_details` (
  `Invoice_detail_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Quote_id` INT(11) UNSIGNED NULL,
  `Order_id` INT(11) UNSIGNED NULL,
  `product_id` INT(11) UNSIGNED NULL,
  `attibute_id` INT(11) UNSIGNED NULL,
  `price` FLOAT NULL,
  `discount` FLOAT NULL,
  `comments` TEXT NULL,
  `quantity` INT(11) UNSIGNED NULL,
  `price_book_id` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`Invoice_detail_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`party_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`party_type` ;

CREATE TABLE IF NOT EXISTS `QOC`.`party_type` (
  `party_type_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `party_type_name` VARCHAR(255) NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`party_type_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`party`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`party` ;

CREATE TABLE IF NOT EXISTS `QOC`.`party` (
  `party_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `party_type_id` INT(11) UNSIGNED NOT NULL,
  `party_name` VARCHAR(255) NULL,
  `party_type` INT(11) UNSIGNED NULL,
  `partent_party_id` INT(11) UNSIGNED NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`party_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `party_FKIndex1` ON `QOC`.`party` (`party_type_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`Address_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Address_type` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Address_type` (
  `address_type_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `address_type` VARCHAR(255) NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`address_type_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Country` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Country` (
  `country_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Country_name` VARCHAR(255) NULL,
  PRIMARY KEY (`country_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`address` ;

CREATE TABLE IF NOT EXISTS `QOC`.`address` (
  `address_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Country_country_id` INT(11) UNSIGNED NOT NULL,
  `Address_type_address_type_id` INT(11) UNSIGNED NOT NULL,
  `address_type_id` INT(11) UNSIGNED NULL,
  `address1` VARCHAR(255) NULL,
  `address2` VARCHAR(255) NULL,
  `city_id` INT(11) UNSIGNED NULL,
  `pin` INT(11) UNSIGNED NULL,
  `state_id` INT(11) UNSIGNED NULL,
  `countr_id` INT(11) UNSIGNED NULL,
  `party_id` INT(11) UNSIGNED NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`address_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `address_FKIndex1` ON `QOC`.`address` (`Address_type_address_type_id` ASC);

CREATE INDEX `address_FKIndex2` ON `QOC`.`address` (`Country_country_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`contact` ;

CREATE TABLE IF NOT EXISTS `QOC`.`contact` (
  `contact_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contact_type` INT(11) UNSIGNED NULL,
  `contact` VARCHAR(255) NULL,
  `party_id` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`contact_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`Organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Organization` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Organization` (
  `Organization_id` DOUBLE NOT NULL AUTO_INCREMENT,
  `Organization_name` VARCHAR(255) NOT NULL,
  `Parent_Organization_id` DOUBLE NULL,
  `Effective_date` DATE NULL,
  `End_date` DATE NULL,
  `Party_id` INT(11) UNSIGNED NULL,
  `address_id` INT(11) UNSIGNED NULL,
  `contact_id` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`Organization_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `Organization_FKIndex1` ON `QOC`.`Organization` (`address_id` ASC);

CREATE INDEX `Organization_FKIndex2` ON `QOC`.`Organization` (`contact_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`Product_Master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Product_Master` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Product_Master` (
  `Product_Id` DOUBLE NOT NULL AUTO_INCREMENT,
  `Product_Name` VARCHAR(255) NOT NULL,
  `Parent_Product_id` DOUBLE NULL,
  `Organization_id` DOUBLE NULL,
  `Effective_date` DATE NULL,
  `End_date` DATE NULL,
  PRIMARY KEY (`Product_Id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `Product_Master_FKIndex1` ON `QOC`.`Product_Master` (`Organization_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`Product_Attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Product_Attribute` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Product_Attribute` (
  `Attribute_id` DOUBLE NOT NULL AUTO_INCREMENT,
  `Attribute_Name` VARCHAR(255) NOT NULL,
  `Effective_date` DATE NOT NULL,
  `End_Date` DATE NULL,
  `Parent_Attribute_id` DOUBLE NULL,
  `Price` FLOAT NULL,
  `part_number` TEXT NULL,
  PRIMARY KEY (`Attribute_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`quote_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`quote_master` ;

CREATE TABLE IF NOT EXISTS `QOC`.`quote_master` (
  `quote_id` DOUBLE NOT NULL AUTO_INCREMENT,
  `quote_name` VARCHAR(255) NOT NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  `party_id` INT(11) UNSIGNED NULL,
  `address_id` INT(11) UNSIGNED NULL,
  `contact_id` INT(11) UNSIGNED NULL,
  `version` VARCHAR(255) NOT NULL,
  `Price` FLOAT NULL,
  `Discounts` FLOAT NULL,
  `comments` VARCHAR(255) NULL,
  PRIMARY KEY (`quote_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `quote_master_FKIndex1` ON `QOC`.`quote_master` (`party_id` ASC);

CREATE INDEX `quote_master_FKIndex2` ON `QOC`.`quote_master` (`contact_id` ASC);

CREATE INDEX `quote_master_FKIndex3` ON `QOC`.`quote_master` (`address_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`price_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`price_book` ;

CREATE TABLE IF NOT EXISTS `QOC`.`price_book` (
  `price_book_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `price_book_name` TEXT NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`price_book_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`Price_book_attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Price_book_attribute` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Price_book_attribute` (
  `price_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Product_Attribute_Attribute_id` DOUBLE NOT NULL,
  `price_book_id` INT(11) UNSIGNED NOT NULL,
  `price_book_name` TEXT NULL,
  `attribute_id` INT(11) UNSIGNED NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`price_id`, `Product_Attribute_Attribute_id`, `price_book_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `Price_book_attribute_FKIndex1` ON `QOC`.`Price_book_attribute` (`Product_Attribute_Attribute_id` ASC);

CREATE INDEX `Price_book_attribute_FKIndex2` ON `QOC`.`Price_book_attribute` (`price_book_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`quote_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`quote_details` ;

CREATE TABLE IF NOT EXISTS `QOC`.`quote_details` (
  `quote_detail_id` DOUBLE NOT NULL AUTO_INCREMENT,
  `Price_book_attribute_price_book_id` INT(11) UNSIGNED NOT NULL,
  `Price_book_attribute_Product_Attribute_Attribute_id` DOUBLE NOT NULL,
  `Price_book_attribute_price_id` INT(11) UNSIGNED NOT NULL,
  `quote_id` DOUBLE NULL,
  `product_id` DOUBLE NULL,
  `attribute_id` DOUBLE NULL,
  `price` FLOAT NULL,
  `discounts` FLOAT NULL,
  `comments` VARCHAR(255) NULL,
  `quantity` INT(11) UNSIGNED NULL,
  `price_book_id` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`quote_detail_id`, `Price_book_attribute_price_book_id`, `Price_book_attribute_Product_Attribute_Attribute_id`, `Price_book_attribute_price_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `quote_details_FKIndex1` ON `QOC`.`quote_details` (`quote_id` ASC);

CREATE INDEX `quote_details_FKIndex2` ON `QOC`.`quote_details` (`Price_book_attribute_price_id` ASC, `Price_book_attribute_Product_Attribute_Attribute_id` ASC, `Price_book_attribute_price_book_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`state` ;

CREATE TABLE IF NOT EXISTS `QOC`.`state` (
  `state_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Country_country_id` INT(11) UNSIGNED NOT NULL,
  `state_name` VARCHAR(255) NULL,
  `country_id` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`state_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `state_FKIndex1` ON `QOC`.`state` (`Country_country_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`city` ;

CREATE TABLE IF NOT EXISTS `QOC`.`city` (
  `city_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Country_country_id` INT(11) UNSIGNED NOT NULL,
  `city_name` VARCHAR(255) NULL,
  `state_id` INT(11) UNSIGNED NULL,
  `country_id` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`city_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `city_FKIndex1` ON `QOC`.`city` (`Country_country_id` ASC);

CREATE INDEX `city_FKIndex2` ON `QOC`.`city` (`state_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`Product_configuration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Product_configuration` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Product_configuration` (
  `Product_config_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Product_Master_Product_Id` DOUBLE NOT NULL,
  `Product_Attribute_Attribute_id` DOUBLE NOT NULL,
  `Product_id` INT(11) UNSIGNED NULL,
  `Product_name` TEXT NULL,
  `attribute_id` INT(11) UNSIGNED NULL,
  `effective_date` DATE NULL,
  `end_date` DATE NULL,
  `quantity` INT(11) UNSIGNED NULL,
  `Non_standard_text` TEXT NULL,
  PRIMARY KEY (`Product_config_id`, `Product_Master_Product_Id`, `Product_Attribute_Attribute_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

CREATE INDEX `Product_configuration_FKIndex1` ON `QOC`.`Product_configuration` (`Product_Master_Product_Id` ASC);

CREATE INDEX `Product_configuration_FKIndex2` ON `QOC`.`Product_configuration` (`Product_Attribute_Attribute_id` ASC);


-- -----------------------------------------------------
-- Table `QOC`.`Order_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Order_master` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Order_master` (
  `Order_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Quote_id` INT(11) UNSIGNED NULL,
  `Order_status` INT(11) UNSIGNED NULL,
  `Invoice_id` INT(11) UNSIGNED NULL,
  `Percentage_completed` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`Order_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Invoice` (
  `Invoice_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Invoice_date` DATE NULL,
  `Quote_id` INT(11) UNSIGNED NULL,
  `Order_id` INT(11) UNSIGNED NULL,
  `Customer_name` TEXT NULL,
  `Customer_address_line1` TEXT NULL,
  `Customer_address_line2` TEXT NULL,
  `City` TEXT NULL,
  `State` TEXT NULL,
  `Country` TEXT NULL,
  `Invoice_status` INT(11) UNSIGNED NULL,
  `Contact_number` TEXT NULL,
  `Quote_version` TEXT NULL,
  `price` FLOAT NULL,
  `discount` FLOAT NULL,
  `comments` TEXT NULL,
  PRIMARY KEY (`Invoice_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`Invoice_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`Invoice_details` ;

CREATE TABLE IF NOT EXISTS `QOC`.`Invoice_details` (
  `Invoice_detail_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Quote_id` INT(11) UNSIGNED NULL,
  `Order_id` INT(11) UNSIGNED NULL,
  `product_id` INT(11) UNSIGNED NULL,
  `attibute_id` INT(11) UNSIGNED NULL,
  `price` FLOAT NULL,
  `discount` FLOAT NULL,
  `comments` TEXT NULL,
  `quantity` INT(11) UNSIGNED NULL,
  `price_book_id` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`Invoice_detail_id`))
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `QOC`.`ASSET_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`ASSET_TYPE` ;

CREATE TABLE IF NOT EXISTS `QOC`.`ASSET_TYPE` (
  `ASSET_TYPE_ID` DOUBLE NOT NULL,
  `ASSET_TYPE_NAME` VARCHAR(255) NULL,
  PRIMARY KEY (`ASSET_TYPE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`ASSET_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`ASSET_STATUS` ;

CREATE TABLE IF NOT EXISTS `QOC`.`ASSET_STATUS` (
  `ASSET_STATUS_ID` DOUBLE NOT NULL,
  `ASSET_STATUS_NAME` VARCHAR(255) NULL,
  PRIMARY KEY (`ASSET_STATUS_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`ASSET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`ASSET` ;

CREATE TABLE IF NOT EXISTS `QOC`.`ASSET` (
  `ASSET_ID` DOUBLE NOT NULL,
  `ASSET_NAME` VARCHAR(255) NULL,
  `ASSET_STATUS_ID` DOUBLE NULL,
  `ORGANIZATION_ID` DOUBLE NULL,
  `ASSET_TYPE_ID` DOUBLE NULL,
  `ASSET_FROM_ADDRESS` TEXT NULL,
  `ASSET_TO_ADDRESS` TEXT NULL,
  `MASTER_COMPANY_ID` DOUBLE NULL,
  `ASSET_PURCHASE_ORDER_NO` VARCHAR(255) NULL,
  `ASSET_PO_DATEl` DATE NULL,
  PRIMARY KEY (`ASSET_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`ASSET_PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`ASSET_PRODUCT` ;

CREATE TABLE IF NOT EXISTS `QOC`.`ASSET_PRODUCT` (
  `ASSET_PRODUCT_ID` DOUBLE NULL,
  `ASSET_PRODUCT_SUPPLIER_NAME` VARCHAR(255) NULL,
  `ASSET_PRODUCT_NAME` MEDIUMTEXT NULL,
  `ASSET_PRODUCT_DESC` TEXT NULL,
  `ASSET_PRODUCT_SUPPLIER_ID` MEDIUMTEXT NULL,
  `ASSET_PRODUCT_UOM` DOUBLE NULL,
  `ASSET_PRODUCT_CATEGORY` MEDIUMTEXT NULL,
  `ASSET_PRODUCT_COST` FLOAT NULL,
  `ASSET_PRODUCT_MARGIN_PERCENTAGE` FLOAT NULL,
  `ASSET_PRODUCT_DISCOUNT_THRESHOLD` FLOAT NULL,
  `ASSET_PRODUCT_GST` FLOAT NULL,
  `ASSET_PRODUCT_CAVEATS` LONGTEXT NULL,
  `ASSET_PRODUCT_MANDATORY_PARTS` TEXT NULL COMMENT 'WE SHOULD HAVE \nCOMMA SEPRATED\nVALUES TO READ WITH PRODUCT ID',
  `NOTES` VARCHAR(45) NULL,
  `ASSET_ID` DOUBLE NULL,
  `MASTER_COMPANY_ID` DOUBLE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`TASK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`TASK` ;

CREATE TABLE IF NOT EXISTS `QOC`.`TASK` (
  `TASK_ID` DOUBLE NOT NULL,
  `TASK_DESC` VARCHAR(255) NULL,
  `TASK_CREATE_DATE` DATE NULL,
  `TASK_END_DATE` DATE NULL,
  `TASK_STATUS_ID` DOUBLE NULL,
  `TASK_RAG` VARCHAR(255) NULL,
  `TASK_COMMENTS` TEXT NULL,
  `USER_ID` DOUBLE NULL,
  `MASTER_COMPANY_ID` DOUBLE NULL,
  PRIMARY KEY (`TASK_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QOC`.`TASK_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QOC`.`TASK_STATUS` ;

CREATE TABLE IF NOT EXISTS `QOC`.`TASK_STATUS` (
  `TASK_STATUS_ID` DOUBLE NOT NULL,
  `TASK_STATUS_NAME` VARCHAR(255) NULL,
  PRIMARY KEY (`TASK_STATUS_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

